### ISSUE TITLE
Same links are repeated throughout sections

### ISSUE THREAD

**Issue by winterdamsel** [DesignOpen/designopen.github.io#144]
'Designing in the open' comes up under 'benefits', 'blog' and 'challenges'.

'UK Goverment Redesign', 'Sparkbox Redesign', 'Penn State University Redesign', 'New Internationalist Redesign', 'Mozilla Redesign', 'How To Build An App Project', 'Greater Pittsburgh Community Food Bank Website Redesign', 'Drupal UX' and 'CSS-Tricks Redesign' are in 'example' and 'opendesign'.

Gratisography and EIGHT.psd in 'example' and 'source'.

DanielMall.com in 'design' and 'source'.

A List Together in 'design' and 'blog'.

Too many links are repeated and perhaps it would be a good idea to either add tags (if they really have to be in 2 sections) or delete them from the one they have less things in common with.

**Comment by alicjasalamon** [comment]
As suggested during the meeting, it might be possible to assign just one tag to each resource so the links in the "Resources" section are not duplicated. 
While working on that I've realized that doing so is against the "nature of tags", because they usually come in groups (like Stack Overflow tags or Twitter hashtags).

I can think of two ways to solve this problem:
1. Using the current concept of tags, but providing a different way of displaying them. 
List of resources with items looking more or less like this:

![image](https://cloud.githubusercontent.com/assets/3893215/5991669/7162fb6a-a9b3-11e4-98d3-c5be7ae4898b.png)

2. Turning "tags" into "category", creating a set of some reasonable categories, assigning just one category to one resource.

**Comment by GarthDB** [comment]
you're awesome.

**Comment by GarthDB** [comment]
http://media.giphy.com/media/2UpzC3iPenf44/giphy.gif
